<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ConfigController;
use App\Http\Controllers\ConfigurationController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\FarmerController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ShippingController;
use App\Http\Controllers\ShippingMethod;
use App\Http\Controllers\SizeController;
use App\Http\Controllers\TypeConfigController;
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => ''], function () {
    Route::get('', [CustomerController::class, 'index'])->name('index');
    Route::get('/about', [CustomerController::class, 'about'])->name('about');
    Route::get('/store', [CustomerController::class, 'store'])->name('store');
    Route::get('/store/category={id}', [CustomerController::class, 'store'])->name('cate');
    Route::get('/store/search={keyword}', [CustomerController::class, 'store'])->name('search');
    Route::get('/store/sort={sort}', [CustomerController::class, 'store'])->name('sort');
    Route::get('/store/price={price}', [CustomerController::class, 'store'])->name('filter');
    Route::get('/store/getbyCate', [CustomerController::class, 'getByCate'])->name('getByCate');
    Route::get('/store/getbySort', [CustomerController::class, 'getbySort'])->name('getbySort');
    Route::get('/store/getbyPrice', [CustomerController::class, 'getbyPrice'])->name('getbyPrice');
    Route::get('/productdetail={id}', [CustomerController::class, 'productdetail'])->name('productdetail');
    Route::get('/cart', [CustomerController::class, 'cart'])->name('cart')->middleware('customer');
    Route::post('/updateCart', [CustomerController::class, 'updateCart'])->name('updateCart')->middleware('customer');
    Route::get('/removeCart', [CustomerController::class, 'removeCart'])->name('removeCart')->middleware('customer');
    Route::get('/totalCart', [CustomerController::class, 'totalCart'])->name('totalCart');
    Route::get('/countCart', [CustomerController::class, 'countCart'])->name('countCart');
    Route::get('/getCountWishList', [CustomerController::class, 'getCountWishList'])->name('getCountWishList');
    Route::get('/removeAllCart', [CustomerController::class, 'removeAllCart'])->name('removeAllCart')->middleware('customer');
    Route::get('/cart={id}', [CustomerController::class, 'addCart'])->name('addCart')->middleware('customer');
    Route::get('/blog', [CustomerController::class, 'blog'])->name('blog');
    Route::get('/blogdetail={id}', [CustomerController::class, 'blogdetail'])->name('blogdetail');
    Route::get('/contact', [CustomerController::class, 'contact'])->name('contact');
    Route::get('/login', [CustomerController::class, 'login'])->name('login');
    Route::get('/success', [CustomerController::class, 'success'])->name('success');
    Route::post('/login', [CustomerController::class, 'login_post'])->name('login_post');
    Route::post('/register', [CustomerController::class, 'register_post'])->name('register_post');
    Route::get('/logout', [CustomerController::class, 'logout'])->name('logout');
    Route::get('/profile', [CustomerController::class, 'profile'])->name('profile')->middleware('customer');;
    Route::post('/updateProfile', [CustomerController::class, 'updateProfile'])->name('updateProfile')->middleware('customer');
    Route::get('/wishlist', [CustomerController::class, 'wishlist'])->name('wishlist')->middleware('customer');
    Route::get('/addWishlist={id}', [CustomerController::class, 'addWishlist'])->name('addWishlist')->middleware('customer');
    Route::get('/removewish={id}', [CustomerController::class, 'removewish'])->name('removewish')->middleware('customer');
    Route::post('/commentblog', [CustomerController::class, 'comment'])->name('commentblog')->middleware('customer');
    Route::post('/rep', [CustomerController::class, 'rep'])->name('rep')->middleware('customer');
    Route::post('/vote', [CustomerController::class, 'vote'])->name('vote')->middleware('customer');
    Route::get('/addProdetail', [CustomerController::class, 'addProdetail'])->name('addProdetail')->middleware('customer');
    Route::get('/blog/name={name}', [CustomerController::class, 'blog_search'])->name('blog_search');
    Route::get('/getCoupon', [CustomerController::class, 'getCoupon'])->name('getCoupon');
    Route::get('/getDistricts', [CustomerController::class, 'getDistricts'])->name('getDistricts');
    Route::get('/getCommunes', [CustomerController::class, 'getCommunes'])->name('getCommunes');
    Route::get('/ship', [CustomerController::class, 'ship'])->name('ship');
    Route::get('/checkout', [CustomerController::class, 'checkout'])->name('checkout')->middleware('customer');
    Route::get('/totalamount', [CustomerController::class, 'totalamount'])->name('totalamount');
    Route::get('/forgot_password', [CustomerController::class, 'forgot_password'])->name('forgot_password');
    Route::post('/forgot_post', [CustomerController::class, 'forgot_post'])->name('forgot_post');
    Route::get('/typecode', [CustomerController::class, 'typecode'])->name('typecode');
    Route::post('/postcode', [CustomerController::class, 'postcode'])->name('postcode');
    Route::get('/changepassword', [CustomerController::class, 'changepassword'])->name('changepassword');
    Route::post('/post_password', [CustomerController::class, 'post_password'])->name('post_password');
    Route::post('/post_contact', [CustomerController::class, 'post_contact'])->name('post_contact');
    Route::post('/post_order', [CustomerController::class, 'post_order'])->name('post_order');
    Route::get('/banking', [CustomerController::class, 'banking'])->name('banking');
    Route::get('/order_tracking', [CustomerController::class, 'order_tracking'])->name('order_tracking');
    Route::get('/order_tracking/{id}', [CustomerController::class, 'order_tracking_detail'])->name('order_tracking_detail');
});
Route::get('/admin_login', [AdminController::class, 'login'])->name('admin_login');
Route::post('/admin_login', [AdminController::class, 'post_login'])->name('post_login');
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('home', [AdminController::class, 'index'])->name('index_admin');
    Route::post('update_admin', [AdminController::class, 'update_admin'])->name('update_admin');
    Route::resource('category', CategoryController::class);
    Route::resource('product', ProductController::class);
    Route::resource('size', SizeController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('coupon', CouponController::class);
    Route::resource('shipping', ShippingController::class);
    Route::resource('brand', BrandController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('farmer', FarmerController::class);
    Route::resource('config', ConfigController::class);
    Route::resource('order', OrderController::class);
    Route::resource('shippingmethod', ShippingMethod::class);
    Route::get('contact', [ContactController::class, 'index'])->name('contact.index');
    Route::get('profile', [AdminController::class, 'profile'])->name('profile.admin');
    Route::post('getData', [AdminController::class, 'getData'])->name('getData');
    Route::get('contact_reply/{id}', [ContactController::class, 'contact_reply'])->name('contact.contact_reply');
    Route::post('reply/{id}', [ContactController::class, 'post_reply'])->name('contact.post_reply');
    Route::get('logout', [AdminController::class, 'logout'])->name('admin_logout');
    Route::get('comment', [AdminController::class, 'comment'])->name('comment');
    Route::get('removecomment={id}', [AdminController::class, 'removecomment'])->name('removecomment');
    Route::get('accept={id}', [AdminController::class, 'accept'])->name('accept');
    Route::get('order_filter', [AdminController::class, 'order_filter'])->name('order_filter');
    Route::get('update_order', [AdminController::class, 'update_order'])->name('update_order');
    Route::get('order={value}', [AdminController::class, 'order'])->name('order');
});
